config/routes.rb
Rails.application.routes.draw do
  devise_for :users 
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
   root "notes#index"
  resources :notes
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :user
  validates :title , presence: true
  validates :description , presence: true
  validates :date, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :notes, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
 
 
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :authenticate_user!
  
  def index 
    @notes = current_user.notes
  end
  def show
    @note = Note.find(params[:id])
  end
  def new
    @note = Note.new
  end
  def create
     @note = current_user.notes.build(note_params)
     @note.user = current_user
     if @note.save
     redirect_to notes_path, notice: 'Note was successfully created.'
     else
     render :new
     end
end
def edit
  @note = Note.find(params[:id])
  end
  def update
    @note = Note.find(params[:id])
    if @note.update(note_params)
      redirect_to notes_path, notice: 'Note was successfully updated.'
      else
        render :edit
        end
        end
        def destroy
          @note = Note.find(params[:id])
          @note.destroy
          redirect_to notes_path, notice: 'Note was successfully destroyed.'
          end

private 
def note_params
  params.require(:note).permit(:title, :description, :date)
end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  protected

  def after_sign_up_path_for(resource)
    new_user_session_path # Redirect to sign in page
  end
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Notesapp" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>  
    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  
    <%= yield %>
  </body>
</html>

app/views/notes/_form.html.erb
<%= form_with model:@note do |form|%>
   <div class="field">
  <%= form.label :title %>
  <%= form.text_field :title %>
  </div>
  <div class="field">
  <%=form.label :description %>
  <%= form.text_area :description %>
  </div>
  <div class="field">
  <%= form.label :date %>
  <%= form.date_field :date %>
  <div class="field">
  <%= form.submit %>
  </div>
  <%end%>

app/views/notes/edit.html.erb
<%= render partial: "partial/header"%>
<body>
<h1>Edit Note</h1>

<div class="form-container"> 
<%= render "form", note: @note %>
<%= button_to "Home",notes_path ,method: :get %>  
</div>
</body>

app/views/notes/index.html.erb
<body>
<%= render partial: "partial/header"%>
<div class ="form-container">
<% @notes.each do |note|%>
<li>
<%= link_to note.title,note%>
</li>
<%end%>
<%=button_to "Create Notes","/notes/new",method: :get %>

  </div>
  </body>

app/views/notes/new.html.erb
<body>
<%= render partial: "partial/header"%>
 <h1> Create Note </h1>
<div class="form-container">
 
<%= render "form", note: @note %>
<%= button_to "Home",notes_path ,method: :get %>  
</div>
</body>

app/views/notes/show.html.erb
<div class="form-container">
<p>Title:<%= @note.title %></p>
<p>Description: <%= @note.description %></p>
<p>Date:<%= @note.date %></p>
<%= button_to "Edit", edit_note_path ,method: :get%>
<%= button_to "Destroy", note_path(@note),method: :delete %>
             
<%= button_to "Home",notes_path ,method: :get %>                  
</div>

app/views/partial/_header.html.erb
<nav class="navbar">
    <div class="navbar-left">
      <h1 class="navbar-title">Notes App</h1>
    </div>
    
    <% if user_signed_in? %>
      <div class="navbar-right">
        <p class="welcome-message">Welcome, <%= current_user.email %> </p>
        <%= button_to 'Logout', destroy_user_session_path, method: :delete, class: "btn-logout" %>
      </div>
    <% end %>
  </nav>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>